---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dynamic-route53.fullname" . }}-config
  labels:
    {{- include "dynamic-route53.labels" . | nindent 4 }}
data:
{{- tpl ((.Files.Glob "configmap/**").AsConfig) . | nindent 2 }}
