---
name: Build container image
on:
 push:
   branches: [main]

env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-and-push-container:
    runs-on: ubuntu-latest
    steps:
      - name: Install podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman buildah qemu-user-static
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: dynamic-route53
          tags: latest ${{ github.sha }}
          archs: amd64, arm64
          containerfiles: |
            ./Containerfile
          oci: true
      - name: Push to ghcr.io
        id: push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
          extra-args: |
            --disable-content-trust
